version: "3.9"
   
services:  
  web:
    build: .
    container_name: docker-python-django-web-dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
    ports:
      - "8080:8000"
    env_file:
      - ./.env.web.dev
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    networks:
      - docker-python-django

  db:
    image: postgres:13
    container_name: docker-python-django-db-dev
    volumes:
      - ./data/db-dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 12
    env_file:
    - ./.env.db.dev
    networks:
      - docker-python-django

networks:
  docker-python-django:
    name: docker-python-django-dev
    driver: bridge